/*****************************************************************************
                   C A E L U S   I N C L U D E   M O D U L E
                    	(c)Copyright 1991 CAELUS, Inc.
                     A L L   R I G H T S   R E S E R V E D
==============================================================================
                      M O D U L E   D E S C R I P T I O N
------------------------------------------------------------------------------

	Language definition constants - this file is generated by yacc from
		the language definition in gram.y

==============================================================================
               M O D I F I C A T I O N   H I S T O R Y
------------------------------------------------------------------------------
 	DATE		WHO	DESCRIPTION
 	--------	----	----------------------------------------------
	02/??/93	MDH	Re-generated
	01/21/94	MDH	Re-generated for addition of FAINPUT
	06/01/97	KAB     Re-generated for Eunice. (consistency, no chng)

==============================================================================
               M O D U L E   B E G I N S   H E R E
*****************************************************************************/
static char yacc_SccsId[] = "@(#)include yacc.h  Version 5.2  06/05/97";

# define ABS 257
# define ALL 258
# define ARCCOS 259
# define ARCSIN 260
# define ARCTAN 261
# define ASORT 262
# define AT 263
# define ATN 264
# define BELL 265
# define BI 266
# define BIN 267
# define CH 268
# define COL 269
# define CON 270
# define COS 271
# define DATE 272
# define DIM 273
# define DSORT 274
# define EXP 275
# define FAC 276
# define FS 277
# define FL 278
# define HEX 279
# define HEXOF 280
# define IDN 281
# define INT 282
# define INV 283
# define KEY 284
# define LEN 285
# define LGT 286
# define LOG 287
# define MASK 288
# define MAX 289
# define MIN 290
# define MOD 291
# define NUM 292
# define PAGE 293
# define PD 294
# define PIC 295
# define POS 296
# define RANGE 297
# define RND 298
# define ROUND 299
# define SGN 300
# define SIN 301
# define SIZE 302
# define SKIP 303
# define SQR 304
# define STR 305
# define TAB 306
# define TAN 307
# define TIME 308
# define TRN 309
# define VAL 310
# define XX 311
# define ZER 312
# define NOFUN 313
# define ADD 314
# define ADDC 315
# define AND 316
# define BOOL0 317
# define BOOL1 318
# define BOOL2 319
# define BOOL3 320
# define BOOL4 321
# define BOOL5 322
# define BOOL6 323
# define BOOL7 324
# define BOOL8 325
# define BOOL9 326
# define BOOLA 327
# define BOOLB 328
# define BOOLC 329
# define BOOLD 330
# define BOOLE 331
# define BOOLF 332
# define OR 333
# define XOR 334
# define ACCEPT 335
# define ADDR 336
# define AL 337
# define ALT 338
# define BEG 339
# define BLKSIZE 340
# define BLOCKS 341
# define CALL 342
# define CLEAR 343
# define CLOSE 344
# define COM 345
# define CONSEC 346
# define CONVERT 347
# define COPY 348
# define CRT 349
# define DATA 350
# define DEFFN 351
# define DEF 352
# define DEGREES 353
# define DELETE 354
# define DENSITY 355
# define DISPLAY 356
# define DPACK 357
# define DUP 358
# define ELSE 359
# define END 360
# define EOD 361
# define EXTEND 362
# define FILE0 363
# define FAINPUT 364
# define FILESEQ 365
# define FMT 366
# define FN 367
# define FOR 368
# define FORM 369
# define FROM 370
# define GE 371
# define GET 372
# define GO 373
# define GOSUB 374
# define GOTO 375
# define GRADS 376
# define HEXPACK 377
# define HEXPRINT 378
# define HEXUNPACK 379
# define HOLD 380
# define IF 381
# define IL 382
# define INDEXED 383
# define INIT 384
# define INPUT 385
# define INTO 386
# define IO 387
# define IOERR 388
# define IPACK 389
# define KEY0 390
# define KEYLEN 391
# define KEYPOS 392
# define KEYS 393
# define LE 394
# define LET 395
# define LIBRARY 396
# define LINE 397
# define MASK0 398
# define MAT 399
# define NE 400
# define NEG 401
# define NEXT 402
# define NL 403
# define NOALT 404
# define NODISPLAY 405
# define NOGETPARM 406
# define NOT 407
# define ON 408
# define OPEN 409
# define OUTPUT 410
# define UNPACK 411
# define PACK 412
# define PAUSE 413
# define PI 414
# define POOL 415
# define PRINT 416
# define PRINTER 417
# define PUT 418
# define RADIANS 419
# define READ 420
# define RECORD 421
# define RECSIZE 422
# define REDIM 423
# define REM 424
# define REPLACING 425
# define RESTORE 426
# define RETURN 427
# define REWRITE 428
# define ROTATE 429
# define ROTATEC 430
# define SCREEN 431
# define SEARCH 432
# define SELECT 433
# define SHARED 434
# define SIZE0 435
# define SPACE 436
# define SPCLINP 437
# define STEP 438
# define STOP 439
# define SUB 440
# define TAPE 441
# define THEN 442
# define TIMEOUT 443
# define TITLE 444
# define TO 445
# define TRAN 446
# define USING 447
# define VAR 448
# define VARC 449
# define VOLUME 450
# define WRITE 451
# define WS 452
# define bcd 453
# define img 454
# define lit2 455
# define lit1 456
# define num 457
# define picture 458
# define var_flt 459
# define var_int 460
# define var_str 461
# define hexnum 462
# define parent 463
# define WRONG 464
